# Generated by Django 6.0.6 on 2026-06-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
